# Generated by Django 3.2.6 on 2021-11-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idComic', models.IntegerField()),
                ('digitalId', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('issueNumber', models.IntegerField()),
                ('variantDescription', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('isbn', models.CharField(max_length=50)),
                ('upc', models.CharField(max_length=50)),
                ('diamondCode', models.CharField(max_length=50)),
                ('ean', models.CharField(max_length=50)),
                ('issn', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('pageCount', models.IntegerField()),
            ],
        ),
    ]
