# Generated by Django 3.2.6 on 2022-01-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('startYear', models.IntegerField(null=True)),
                ('endYear', models.IntegerField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('issueNumber', models.IntegerField(blank=True, null=True)),
                ('variantDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('upc', models.CharField(blank=True, max_length=50, null=True)),
                ('diamondCode', models.CharField(blank=True, max_length=50, null=True)),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('issn', models.CharField(blank=True, max_length=50, null=True)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('pageCount', models.IntegerField(null=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marvel.serie')),
            ],
        ),
    ]
