# Generated by Django 3.2.6 on 2021-11-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='diamondCode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='digitalId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='ean',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='format',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='isbn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='issn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='issueNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='pageCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='upc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comic',
            name='variantDescription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
